# agenix recipients for the Timestone sub-flake secrets.
#
# The .age files live next to this file under secrets/timestone/ and ARE
# committed (ciphertext only): the daily auto-update re-evaluates this flake
# from the PUBLIC GitHub repo, so the encrypted blobs must be present in the
# fetched tree. Plaintext exists nowhere — only office + the nodes can decrypt.
#
# Recipients:
#   office  — the office machine's age identity (~/.ssh/age.pub); lets the
#             operator edit secrets locally (`nix run .#agenix -e`).
#   nodes   — a single SHARED age keypair `timestone-age-identity`, generated by
#             the operator at Stage 3 (age-keygen). Its public half is pasted
#             below; the private half is pushed to both nodes as
#             /etc/ssh/age-identity via nixos-anywhere --extra-files so agenix
#             can decrypt at FIRST activation (node ssh host keys don't exist
#             until after first boot, so they can't be recipients for install).
#             Per-node ssh host pubkeys may be appended later for fidelity.
let
  office = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHvBxDHUfnnQSNGr3K35hacUDFzveraQ3F0JKcwUDHr5 john@office";
  # FILL at Stage 3.1 with `age-keygen -y age-identity` output (starts age1…):
  nodeAgeIdentity = "age1PLACEHOLDER...";
  allKeys = [office nodeAgeIdentity];
in {
  "timestone/k3s-token.age".publicKeys = allKeys;
  "timestone/cloudflared-tunnel.age".publicKeys = allKeys;
  # Optional — only when home S3 backups are enabled this phase; omit the file
  # and the backups ArgoCD Application otherwise.
  "timestone/home-s3-rclone.age".publicKeys = allKeys;
}
