apiVersion: v1alpha1
kind: KubeletConfig
config:
    systemReserved:
        cpu: 100m
        memory: 256Mi
    kubeReserved:
        cpu: 150m
        memory: 512Mi
extraArgs:
    cloud-provider: external
